sudo: false
dist: trusty
language: java

os:
- linux
- osx

jdk:
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
- oraclejdk-ea

matrix:
  exclude:
  - os: osx
    jdk: oraclejdk-ea # Distributed as a "dmg"

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
