sudo: false
dist: trusty
language: java

os:
- linux
- osx

jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
- oraclejdk-ea

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
