language: java

sudo: false
dist: trusty

os:
- linux
- osx

jdk:
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
- oraclejdk-ea

matrix:
  include:
  - os: linux
    jdk: openjdk8
  allow_failures:
  - os: osx
    jdk: oraclejdk-ea # TODO Download, install and use "dmg" on Travis CI

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
