language: java
sudo: false
dist: trusty

before_script:
- unset -f cd
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: OpenJDK
    env: JDK=OpenJDK 9
    script: source ./install-jdk.sh -F 9
  - stage: OpenJDK
    env: JDK=OpenJDK 10
    script: source ./install-jdk.sh -F 10
  - stage: OpenJDK
    env: JDK=OpenJDK 11
    script: source ./install-jdk.sh -F 11
  - stage: Oracle
    env: JDK=Oracle JDK 10
    script: source ./install-jdk.sh -F 10 -L BCL
  - stage: Oracle
    env: JDK=Oracle JDK 11
    script: source ./install-jdk.sh -F 11 -L BCL
#  - stage: adoptopenjdk.net/hotspot
#    - script: source install-jdk.sh --url $(curl --silent https://api.adoptopenjdk.net/openjdk9/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
#    - script: source install-jdk.sh --url $(curl --silent https://api.adoptopenjdk.net/openjdk10/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
#  - stage: adoptopenjdk.net/eclipse-openj9
#    - script: source install-jdk.sh --url $(curl --silent https://api.adoptopenjdk.net/openjdk9-openj9/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
#    - script: source install-jdk.sh --url $(curl --silent https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)

#install:
#- echo "The default Travis install script is being skipped!"

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
