language: java

sudo: false
dist: trusty

os:
- linux
- osx

jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
- oraclejdk-ea

matrix:
  exclude:
  - os: osx
    jdk: openjdk8
  - os: osx
    jdk: oraclejdk-ea # TODO Download, install and use "dmg" on Travis CI
  include:
  - os: linux
    env: ADOPT=HotSpot
    install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --verbose --url $(curl --silent https://api.adoptopenjdk.net/openjdk10/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
  - os: linux
    env: ADOPT=OpenJ9
    install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --verbose --url $(curl --silent https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)

before_install:
- unset _JAVA_OPTIONS

install:
- echo "The default Travis install script is being skipped!"

before_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}

script:
- java -version

after_script:
- ls ${JAVA_HOME}
- cat "${JAVA_HOME}/release"
